name: On pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Check ktLint
      run: ./gradlew ktLintCheck
    - name: Build
      run: ./gradlew build
