name: On push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: clean
      run: ./gradlew clean
    - name: check ktLint
      run: ./gradlew ktLintCheck
